/*
Author: Diego Peña
Creation Date: 17-05-2020
Last Modified: 19-05-2020, 12:15 pm VET
*/

/*If a matrix is represented as a 1D array, in row major order, given the number of columns of the matrix and the coordinates
of an element, this function returns the index corresponding to the element in the 1D Array*/
int getMatrixIndex(int ncolumns, int row, int column);

/*When recovering the supersequence, if the number of either the row or the column reaches zero, it means all the characters
in one of the two strings are already in the part of thesupersequence we have recovered, so we must finish reconstructing 
the rest by filling the remaining spots with the characters in the other string not yet in the sequence*/
void finish_supersequence(char * supersequence, char * str, int seq_index, int str_index);

/*Using the DP Matrix generated by shortest_common_supersequence, along with the strings for which we want to solve the 
problem, the size of the supersequence and the coordinates of the leftmost corner of the matrix, it reconstructs the
supersequence that anwers the problem and stores it in the supersequence variable
NOTE: I decided it was more convenient to pass the size of the supersequence as an argument to avoid searching for it
in the matrix for a second time, since shortest_common_subsequence does it a few lines before calling recover*/
void recover(char * supersequence, char * str1, char * str2, int * seq_table, int seq_index, int row, int col);

/*Uses DP to determinate the shortest common subsequence between str1 and str2*/
char * shortest_common_supersequence(char * str1, char * str2);